// Generated by `npx prisma generate` — run `npm run db:generate` first if you see a TS error here.
// The client lives at be/generated/prisma/ (outside src/ so tsc doesn't touch it).
// @ts-ignore
import { PrismaClient } from '../../generated/prisma/client.js';
import { PrismaPg } from '@prisma/adapter-pg';

type PrismaClientInstance = InstanceType<typeof PrismaClient>;
const globalForPrisma = globalThis as unknown as { prisma?: PrismaClientInstance };

function createPrismaClient(): PrismaClientInstance {
  const isProduction = process.env.NODE_ENV === 'production';
  const adapter = new PrismaPg({
    connectionString: process.env.DATABASE_URL!,
    ...(isProduction && { ssl: { rejectUnauthorized: false } }),
  });
  // @ts-ignore — adapter typing resolves correctly after prisma generate
  return new PrismaClient({ adapter });
}

export const prisma: PrismaClientInstance =
  globalForPrisma.prisma ?? createPrismaClient();

if (process.env.NODE_ENV !== 'production') {
  globalForPrisma.prisma = prisma;
}
