services:
  - type: web
    name: hamro-store-be
    env: node
    buildCommand: yarn install --immutable && yarn build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
